apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: storage-cluster
spec:
  annotations:
    openshift.io/scc: anyuid
  coherence:
    metrics:
      # this enables Coherence metrics so that you can obtain various metrics
      # or you can do things like get Prometheus to poll for metrics
      enabled: true
    management:
      # this enables the Coherence REST management API
      enabled: true
  # The ports section is where you need to add ports that you want to expose
  # using Services so that they can be accessed by clients.
  ports:
    # This will create a Service to expose Coherence metrics on the default
    # metrics port 9612
    - name: metrics
      serviceMonitor:
        enabled: true
    # This will create a Service to expose the Coherence REST management API
    # on the default metrics port 30000
    - name: management
    # This will create a Service to expose the Coherence Extend on port 20000
    # This can be used by clients to connect to caches.
    - name: extend
      port: 20000
